### ISSUE TITLE
error: the only supported value for ONION_VERSION is 3

### ISSUE THREAD

**Issue by mexicozone** [alecmuffett/eotk#104]
Hello! I'm use this manual for install EOTK on Ubuntu 20.04 server:

```
git clone https://github.com/alecmuffett/eotk.git
cd eotk
./opt.d/build-ubuntu-20.04.sh
```
But I have this error when use command `./eotk gen`:

```
root@Atlas:~/eotk# ./eotk gen
error: the only supported value for ONION_VERSION is 3
```

**Comment by spaceneb** [comment]
Download [1.5](https://github.com/alecmuffett/eotk/tree/v1.5)

**Comment by alecmuffett** [comment]
Sorry about this. I am currently out of action with flu or something, but I
will try to push a branch with a fix by the weekend.

**Comment by alecmuffett** [comment]
Fixed, thanks for the report!

**Comment by alecmuffett** [comment]
p.s. Covid sucks.
