### ISSUE TITLE
unknown directive "subs_filter_types"

### ISSUE THREAD

**Issue by Jen111** [alecmuffett/eotk#2]
./eotk start <website>
`2017/02/09  [emerg] 472#472: unknown directive "subs_filter_types" in /home/$USER/Desktop/eotk/projects.d/<website>.d/nginx.conf:41`

am i missing nginx dependencies? i'm new to nginx, not sure if `pacman -S nginx` will include everything i need.

$ uname -a
`Linux unknown 4.9.7-1-ARCH #1 SMP PREEMPT Wed Feb 1 19:33:40 CET 2017 x86_64 GNU/Linux`

$ nginx -h
`nginx version: nginx/1.10.3`

**Comment by alecmuffett** [comment]
Hi! Some googling suggests that you are using Arch.  

I have never used Arch, but my experience with Debian is that the default installs of nginx are unlikely to have everything that you need.

If you try this:

* `cd` into `opt.d` 
* edit the two `build-*-on-debian.sh` scripts, commenting out the `aptitude` lines:
```
$ grep aptitude build-*
build-nginx-on-debian.sh:sudo aptitude install -y libpcre3-dev zlib1g-dev libssl-dev || exit 1
build-tor-on-debian.sh:sudo aptitude install -y libevent-dev zlib1g-dev libssl-dev || exit 1
```
* manually satisfy the following 4 dependencies:
  * libevent-dev
  * libpcre3-dev
  * libssl-dev
  * zlib1g-dev
* run the two scripts

...then, in theory, both of the scripts should work; you should be able to run them and use `eotk`

Please try this and let me know how you get on?

**Comment by Jen111** [comment]
i was just tinkering, so i thought it would be simpler to run your scripts in an ubuntu vm. ill close this issue.

sometimes i need to manually stop/start the tor.service using systemctl. otherwise works great! thank you.

**Comment by Jen111** [comment]
oh, also didnt realize your opt.d/ script needed to be run in the first place. you dont mention that in the readme or in your video.

**Comment by alecmuffett** [comment]
BUT I STILL NEED TO KNOW IF IT WORKS ON ARCH!  :-)

**Comment by alecmuffett** [comment]
Also, see the first video at: https://www.youtube.com/watch?v=ti_VkVmE3J4#t=1m58 (1m58s)
