### ISSUE TITLE
Add support for Next generation onion service

### ISSUE THREAD

**Issue by Baccount** [alecmuffett/eotk#23]
Add support for Next generation onion service. The control port for V3 was added in the latest alpha of Tor 0.3.3.1. https://gitweb.torproject.org/torspec.git/tree/proposals/284-hsv3-control-port.txt

more info
https://trac.torproject.org/projects/tor/wiki/doc/NextGenOnions?version=50#IntrotoNextGenOnionServicesakaprop224

https://gitweb.torproject.org/torspec.git/tree/rend-spec-v3.txt

**Comment by alecmuffett** [comment]
STEM also requires v3 Onion support, for OnionBalance to be ported. See https://trac.torproject.org/projects/tor/ticket/25124

**Comment by Baccount** [comment]
@alecmuffett Thanks, #25124 was the bug report I opened.

**Comment by Baccount** [comment]
@alecmuffett The Trac ticket above was closed.
https://trac.torproject.org/projects/tor/ticket/25124#comment:14

**Comment by alecmuffett** [comment]
done, excepting onionbalance. https://twitter.com/AlecMuffett/status/1146909965589843971
