### ISSUE TITLE
Error I keep getting

### ISSUE THREAD

**Issue by Baccount** [alecmuffett/eotk#24]
When I run `./opt.d/install-everything-on-osx.sh` I get this error.

```
Error: homebrew/nginx was deprecated. This tap is now empty as all its formulae were migrated.
+ brew install nginx-full --with-lua-module --with-subs-filter-module --with-headers-more-module
```

**Comment by alecmuffett** [comment]
That's weird, I'll look into it - thanks!

**Comment by alecmuffett** [comment]
Okay, I am pretty sure that you can ignore that Error; it comes from an (apparently now defunct) line in the script:

`brew tap homebrew/nginx`

...which I shall purge soon.  The next line (`brew install ...`) installs all the stuff you need.

Thanks for the headsup!
