### ISSUE TITLE
HTTP Public Key Pinning

### ISSUE THREAD

**Issue by sainslie** [alecmuffett/eotk#3]
I set it up last night and experimented using a domain name I control.

I implement @ietf RFC 7469 to stipulate specific X.509 credentials in @apache on all the domain names I control. @TheTorProject client doesn't connect to the clear-text host-name through the @TheTorProject domain name because the self-signed X.509 credential set up for the @TheTorProject domain name suffix doesn't match.

It also affects @ietf RFC 6797 if the X.509 credential for the clear-text host-name is preloaded in @TheTorProject client. It therefore stops connecting to the clear-text host-name because of the subsequent mismatch. I'd suggest adding the Secure Hash Algorithm 2 output for @TheTorProject domain name to the stipulated X.509 credentials @apache but it's not going to fix it because the self-signed X.509 credential itself is untrusted.

I realize that the configuration I use is uncommon but it is a useful practical demonstration of the  benefit and robustness of @ietf RFC 7469 and @ietf RFC 6797!

@ietf RFC 7469 is a useful mechanism but I feel it also might be detrimental because it could permit identification of a clear-text host-name if it's being used to host both clear-text material and material through @TheTorProject and the Secure Hash Algorithm 2 output is identified through comparing a database of clear-text domain names and their subsequent Secure Hash Algorithm 2 output.

**Comment by ajhaydock** [comment]
If I understand your issue correctly, it sounds like this is because the `public-key-pins` header is being forwarded to the client by `eotk` when it might be more useful to avoid doing that.

Looks to me like adding either:
```nginx
proxy_hide_header public-key-pins;
```
or
```nginx
more_clear_headers "public-key-pins";
```
to the `server{ }` directive of the `nginx.conf` template should fix the issue as then the HPKP header won't be forwarded to users arriving via .onion

There's probably a good argument for masking the `Strict-Transport-Security` header in the same way too, but I'll see what @alecmuffett thinks.

**Comment by alecmuffett** [comment]
I think this is a pointer to me needing to write actual documentation; I already have a couple of switchables:

- `set header_csp_suppress 1`
- `set header_hsts_suppress 1`

...but maybe the HSTS one (at least) should be default-on, and Alex has (I think) spotted a deficiency in the existing code, re the `*pins` headers 

Also, maybe CSP should be rewritten using Lua, not nuked?

**Comment by ajhaydock** [comment]
CSP is an interesting one. I probably wouldn't nuke it completely like the HSTS/HPKP headers, but rewriting it might be a good idea.

Letting CSP headers pass through unencrypted might cause issues if we want to present the client with an onion served over regular HTTP, and the site admin has decided to use something like `img-src https:` in the CSP, which would allow for the loading of image content from any domain, but only over HTTPS.

I don't know how common that sort of policy is, but I've used that particular directive myself before to allow for image embedding and hyperlink thumbnails on a forum-style site (but without allowing the site to serve mixed-content which would result in a yellow HTTPS warning triangle in the client's browser).

**Comment by alecmuffett** [comment]
@sainslie - check the new code :-)

**Comment by alecmuffett** [comment]
Bump?  I plan to close this tomorrow if no further input?
