### ISSUE TITLE
Could not resolve hostname wolfgang

### ISSUE THREAD

**Issue by Finleyyy** [alecmuffett/eotk#31]
I just installed eotk, then I followed "RUNBOOK.md" but after I typed ./eotk ob-remote-nuke-and-push and it's giving me this:

`
:::: remote wolfgang: stop -a ::::
ssh: Could not resolve hostname wolfgang: Name or service not known
:::: rnap wolfgang ::::
ssh: Could not resolve hostname wolfgang: Name or service not known
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(235) [sender=3.1.2]
`

EDIT=I am using a Raspberry Pi 3 with Raspbian
EDIT2=I use only one machine

**Comment by alecmuffett** [comment]
those are demo names, you are supposed to pick your own.
