### ISSUE TITLE
eotk genkey fails with newer Tor version

### ISSUE THREAD

**Issue by qbi** [alecmuffett/eotk#32]
I'm using the recent master of eotk (d25456afb1a9f9e62bfbcf93401296a691a26e80) and Tor version 0.3.5.7. When running `eotk genkey` the script fails, because it seems Tor creates a v3 onion key and `lib.d/generate-onion-key.sh` tries to `mv` the file `private.key` which doesn't exist here. When I do a `export ONION_VERSION=3; ./eotk genkey` the script works without problems. Also when using Tor 0.3.4.7 /and/ without `ONION_VERSION` it also works.

Also when trying `export ONION_VERSION=3; ./eotk config foo.tconf` results in 

> map: 7nn3d7pc62aisbl6yw2dxtiwhbfcige7xnytuydnu6o43ervefbhihad.v3pub: bad onion address

I guess starting it might be a good idea to test for Tor version. The recent v0.3.5.7 started to default to v3 onions. So if the underlying Tor version is equal or larger than this version it might be better to stick to v3 onions. What do you think?

**Comment by alecmuffett** [comment]
I pushed a fix a few hours ago.

**Comment by alecmuffett** [comment]
Also: v3 onions will *probably* not receive support until OnionBalance (or similar) supports v3, because I don't want to be documenting magic temporary exceptions in the config file.

**Comment by qbi** [comment]
Sorry, should've pulled the latest change first. It works now. Thanks.
