### ISSUE TITLE
Globally tweak nginx.conf files

### ISSUE THREAD

**Issue by maxpearl** [alecmuffett/eotk#34]
If a specific tweak in an nginx.conf file is needed for a particular setup, it would be great if that could be applied globally for all projects, either on config or restart.

**Comment by alecmuffett** [comment]
Done.
* latest provides `eotk-site.conf`
* creates it if it does not exist
* uses it to solve NGINX installation on Ubuntu 18.04LTS
* is prepended onto all subsequent `eotk config ...` configurations
