### ISSUE TITLE
redirect_host is rewriting the URL to redirect to

### ISSUE THREAD

**Issue by micahflee** [alecmuffett/eotk#53]
I want `https://join.foo.onion` to redirect to `https://join.theintercept.com` -- basically, to not load the onion site for that subdomain. In my conf file I have:

```
set redirect_host ^(join)\\.,301,https://join.theintercept.com
```

But when I load the `https://join.cxppxsjlgsvtq7liq4byprpbp7lun3z2khkv5miumwalfwmnqxcf2ayd.onion`, I get the header:

```
Location: https://join.cxppxsjlgsvtq7liq4byprpbp7lun3z2khkv5miumwalfwmnqxcf2ayd.onion/
```

When it should be:

```
Location: https://join.theintercept.com
```

**Comment by alecmuffett** [comment]
fixed in #67, merging soon.
