### ISSUE TITLE
Could not generate website

### ISSUE THREAD

**Issue by noodlesatgithub** [alecmuffett/eotk#58]
./eotk gen did not work. `error: tor failed to launch in /Users/emmettkelleher/eotk/secrets.d/__gok6609.dir
cat: /Users/emmettkelleher/eotk/secrets.d/__gok6609.dir/tor.pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
`

**Comment by maxpearl** [comment]
Can you say what your OS/version is, and include steps to recreate the bug?
