### ISSUE TITLE
only http modus?

### ISSUE THREAD

**Issue by vladuta37** [alecmuffett/eotk#59]
Hi,

why is there not a option to mirror only http onion sites? without the https?

i figured it out with much manual mods but a automated mode would be better

**Comment by maxpearl** [comment]
The protocols are _matched_. If the site you are proxying to Tor is https, it will be matched by an onion over ssl. If not, it will be without ssl. Check out the docs on how to deal with certificates.

**Comment by alecmuffett** [comment]
this.
