### ISSUE TITLE
Needs Port for Windows

### ISSUE THREAD

**Issue by bakertaylor28** [alecmuffett/eotk#6]
Can't do anything with the source code in windows. Remember that the general rule is that releases are supposed to be EXECUTABLE INSTALLATION FILES not just mere source code, which should be included under the "code" section of the repository.

**Comment by alecmuffett** [comment]
Maybe some day I'll get a windows machine and experiment.

**Comment by ajhaydock** [comment]
If you're running Windows 10, it [now supports Docker](https://docs.docker.com/docker-for-windows/), so you can probably run this on Windows with a [Debian Dockerfile](https://github.com/ajhaydock/dockerfiles/blob/master/eotk/Dockerfile) without even needing to rewrite Alec's build scripts.

**Comment by SupaNerdo** [comment]
Indeed, Windows 10 also can run native Ubuntu bash, that might be a possible avenue to installation

**Comment by bakertaylor28** [comment]
Mind you I'm running Windows 8.1 32 as Virtual-Box VM on an Ubuntu Machine, where I run all of my servers as Windows VM's which are kept isolated from the host as much as is possible for security reasons.  So anything having to do with windows 10 doesn't help much.
