### ISSUE TITLE
Log files with origin domains

### ISSUE THREAD

**Issue by maxpearl** [alecmuffett/eotk#60]
Currently, the log files on projects that contain multiple domains mapped do not distinguish between the domains that are requested. 

I'm thinking adding something like this:
```
log_format compression '$remote_user [$time_local] %DNS_DOMAIN%'
                           '"$request" $status $body_bytes_sent '
                           '"$http_referer" "$http_user_agent" ';
```
to templates.d/nginx.conf.txt might do the trick?

**Comment by alecmuffett** [comment]
Merged.  Available with the `set log_separate 1` option.
