### ISSUE TITLE
'resty.core' on Rasbian Stretch

### ISSUE THREAD

**Issue by maxpearl** [alecmuffett/eotk#61]
I've installed EOTK on Rasbian Stretch, and it generates onion keys and configures fine, but when I try to start a project, I get this error: 
```
nginx: [alert] failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file './resty/core.lua'
	no file '/usr/local/share/luajit-2.1.0-beta3/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core/init.lua'
	no file './resty/core.so'
	no file '/usr/local/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so') in /home/pi/eotk/projects.d/mp.d/nginx.conf:490
```
In looking at the Raspbian install script, this should theoretically be working.

**Comment by alecmuffett** [comment]
aw hell, they must have updated their dependencies again.

apologies for the inconvenience, i shall have to dig in.

**Comment by alecmuffett** [comment]
work in progress, at last.

**Comment by alecmuffett** [comment]
@maxpearl I have a pair of reworked scripts in https://github.com/alecmuffett/eotk/pull/64 - I will test and merge into master soonish, but if you want to have a go, please do.

**Comment by alecmuffett** [comment]
merged
