### ISSUE TITLE
Deployment of EOTK on Free Software Foundation Europe

### ISSUE THREAD

**Issue by Kreyren** [alecmuffett/eotk#86]
Requesting help/brainstorm with deploying EOTK on FSFE websites, see https://git.fsfe.org/FSFE/fsfe-website/pulls/1756

Namely:
 1. How should it be deployed over EOTK?
 2. Making it easily maintainable
 3. Setting HTTP Headers for Onion-Location (if EOTK handles that)

### FSFE is using SSL/TLS which should be preserved on onions to avoid leaking of sensitive informations[1]

> KREYREEN: websites which are HTTPS should remain HTTPS.  Websites which are HTTP should remain HTTP.  Attempting to convert HTTP to HTTPS (or: vice-versa) on the fly, is painful and inadvisable, because it can break backend expectations. -- Anonymous

SSL Certificate for onion was last time i checked 600USD per year[?] which is hardly an option for any non-profit organization.

> We can look at FSFE and work out whether there is a way for it to be Pure-HTTP-without-S in limited circumstances, and then might connect EOTK to that. -- Anonymous

### DANE is not an option for cert authority
> DANE wont help you in a Tor context since Tor's DNS subsystem is first and foremost not used for .onion's, but also TLSA record lookups aren't supported even for via-exit circuits in Tor. -- Anonymous

> And TLSA over proxied end-points where the client doesn't full-chain validation of the DNSSEC signatures will be a very bad combination. -- Anonymous

### SOOC - Same Origin Onion Certificate[3]
Idea for the future, not an option atm as it needs changes in the Tor Browser

### References
1. https://github.com/alecmuffett/eotk/blob/master/docs.d/security-advisories.d/001-torbrowser.md
2. https://github.com/alecmuffett/eotk/issues/21
3. https://github.com/alecmuffett/onion-dv-certificate-proposal/blob/master/text/draft-muffett-same-origin-onion-certificates.txt

Thanks a lot in advance, ^-^
- Krey

**Comment by maxpearl** [comment]
New option available for EV certificates for onions: https://blog.torproject.org/tls-certificate-for-onion-site

**Comment by Kreyren** [comment]
CC @mxmehl as http://fsfeorg3hsfyuhmdylxrqdvgsmjeoxuuug5a4dv3c3grkxzsl33d3xyd.onion//index.html.en doesn't seem to have encryption outside of onion routing on onion service.

**Comment by Kreyren** [comment]
also closing as the onion service is already deployed.

@maxpearl thanks for heads-up ! ^-^
